---
openapi: 3.0.0
info:
  title: API
  version: 0.0.0
  description: REST API
  license:
    name: MIT
paths:
components:
  responses:
    ErrResponse:
      description: Error response
      properties:
        msg:
          type: string
        request_id:
          type: string
      type: object
